### ISSUE TITLE
클라우드센터 가상머신 연결 주소 생성

### ISSUE THREAD

**Issue by ycyun** [ablecloud-team/ablestack-cockpit#32]
## 개발 개요
클라우드센터 가상머신 연결 주소 생성
## 개발 기능
클라우드센터 가상머신의 cockpit 새창 링크
## 기타
클라우드센터 가상머신의 ip를 /etc/hosts에서 확인

**Comment by Dajeong-Park** [comment]
@박다정 주임

**Comment by Dajeong-Park** [comment]
* cockpit 서비스 실행중인 상태에서 스택 설치 시 9090 포트 이슈로 아래와 같이 cockpit 포트 변경 테스트를 진행하였습니다.
* 기능 개발을 위해 ccvm의 cockpit port 고정이 필요합니다.

cockpit 포트 변경 테스트 
# mkdir -p /etc/systemd/system/websocket.cockpit.d/
# vi /etc/systemd/system/websocket.cockpit.d/listen.conf
# firewall-cmd --add-port=9898/tcp
# firewall-cmd --permanent --add-port=9898/tcp
# semanage port -m -t websm_port_t -p tcp 9898
# sed -i 's/9090/9898/g' /usr/lib/systemd/system/cockpit.socket
# systemctl daemon-reload
# systemctl restart cockpit.socket
